// Generated by CoffeeScript 1.8.0
(function() {
  chrome.browserAction.onClicked.addListener(function(tab) {
    return chrome.tabs.create({
      "url": "../popup.html"
    });
  });

  chrome.contextMenus.onClicked.addListener(function(info, tab) {
    var url;
    url = 'src.html?url=' + info.linkUrl;
    return chrome.windows.create({
      url: url,
      width: 800,
      height: 800
    });
  });

  chrome.contextMenus.create({
    id: 'open',
    title: "md5sum",
    contexts: ['link']
  });

}).call(this);
